-- PHC per Ian Pun, patch up the errorcodes
CREATE TABLE IF NOT EXISTS `billing_on_errorCode` (
  `code` varchar(5) NOT NULL,
  `description` varchar(255) NOT NULL
);

INSERT INTO `billing_on_errorCode` (`code`, `description`) VALUES
('20', 'Resubmit with Manual review documentation '),
('30', 'this service is not a benefit of OHIP'),
('32', 'OHIP records show service(s) on this day claimed previously'),
('33', 'Approved'),
('35', 'OHIP records show this service rendered has been claimed previously (used on  Pay Practitioner duplicate claims)'),
('36', 'OHIP records show this service has been rendered by another Practitioner, Group, LAB'),
('37', 'the listed benefit for this code in 0 LMS units'),
('40', 'this service allowed only once for same patient'),
('48', 'paid in accordance with the OHIP schedule of benefits'),
('49', 'Paid according to the average free for this service ??? independent considerations will be given if clinical records/operative reports are presented'),
('50', 'fee schedule code changed in accordance with OHIP schedule of benefits'),
('51', 'Fee allowed according to the appropriate item in the current Ministry Schedule of Benefits'),
('52', 'Fee-for-service assessed by medical consultant'),
('53', 'fee allowed according to appropriate item in a previous OHIP schedule of benefits'),
('54', 'interim payment- claim under review'),
('55', 'this deduction is an adjustment on an earlier account (applicable only to system generated negates effective May/97'),
('56', 'claim under review'),
('57', 'this payment is an adjustment on an earlier account'),
('58', 'claimed by another physician within group'),
('59', 'practitionerNULLs notification - WCB claims'),
('60', 'not a benefit of the reciprocal medical billing agreement'),
('61', 'OOC claim paid at greater than $9999.99 (prior approval on file)'),
('65', 'service included in approved hospital payment'),
('68', 'hospital accommodation paid at standard ward rate'),
('69', 'elective services paid at 75% of OHIP  schedule of  rates'),
('70', 'OHIP records show corresponding procedure(s) on this day claimed previously by another physician'),
('80', 'technical fee adjustment for hospitals and IHFs'),
('9', 'Fee Schedule Codes used is not correct ??? resubmit using approprate codes from OHIP Schedule of Benefits'),
('A02', 'prev. OBS service'),
('A03', 'MRP Visit already Pd.'),
('A08', 'one assess at delivery'),
('A2A', 'outside of age limit'),
('A2B', 'wrong sex for service'),
('A34', 'multiple dup. claims'),
('A36', 'claimed by other practitioner.'),
('A3E', 'no suce F.S. code'),
('A3F', 'no fee for service'),
('A3G', 'fee billed low - check'),
('A3H', 'max # ser FSM ref MC'),
('A3J', 'fee outside accept range'),
('A3K', 'auto adj. on prev. man ad'),
('A3L', 'Other New Pt. Fee Alrdy Pd'),
('A4A', 'to assess see guideline'),
('A4D', 'ineligible specialty'),
('A4E', 'manual assess - code 9'),
('A4F', 'MRI review by MC'),
('A6A', 'no claims ref file�A'),
('A7A', 'claim no. not found �.A'),
('A81', 'rule error assess & report'),
('A87', 'FSC mismatch'),
('A88', 'Adjustment payment type unequal'),
('A89', 'pay OOP practice # unequal'),
('A8A', 'claim # previous on file'),
('A91', 'maximum 99 pat. ID records'),
('A93', 'maximum 10000 claim item record'),
('A94', 'claim item not on file'),
('A95', 'Claim Item On File'),
('A96', 'claim # previous on file'),
('A97', 'not all items changed'),
('A98', 'pay sub disallowed claim'),
('A99', 'wrong patient info'),
('AC4', 'unacceptable Ref. #'),
('AD1', 'Corresponding procedure not claimed by same or different physician'),
('AD3', 'not allowed with visit'),
('AD4', 'refer to MC'),
('AD5', 'proceedure allowed previously'),
('AD8', 'not allowed alone'),
('AD9', 'Premium Not Allow Alone'),
('ADC', 'add. proc. at 50%'),
('ADD', 'add. proc. at 50%'),
('ADJ', 'These items may not be claimed together'),
('ADM', 'emerg. equiv/other visits'),
('ADP', 'Mutally Exclus Dental'),
('AEV', 'Visit Only Allowed'),
('AF1', 'multiple frac/dis.'),
('AF5', 'fracture. fee incl.'),
('AG1', 'crit. care alrdy PD'),
('AG2', 'crit. care alrdy PD'),
('AH1', 'On-call Admit Same Day'),
('AH2', 'Hosp. Assess. Other Phys'),
('AH5', 'Admit Date Mismatch'),
('AH6', 'emerg. assess. same day'),
('AH7', 'hosp. assess. same day'),
('AH8', 'invalid ADM date/hosp #'),
('AH9', 'diagnostic service same day'),
('AHA', 'FSC and Time Period Mismatch'),
('AHB', 'overlapping visits'),
('AHD', 'extra visits in wk/mth'),
('AHE', '2 specialties, same period'),
('AHF', 'con/sup care same period'),
('AI4', 'claimed by other IHF/PHY'),
('AMM', 'Max LTC Monthly Fee Apply'),
('AMO', 'multiple surgery. other dr.'),
('AMS', 'multiple procedures'),
('AP', 'this payment is in accordance with legislation - if you disagree with the payment you may appeal to the General Manager'),
('AP2', 'max fee premium/NB care'),
('AP4', 'NIC only allowed'),
('ARD', 'possible duplicate with RMBS'),
('ARF', 'Technical service code requires referring physician'),
('AS8', 'pre-op Cons/Assess'),
('AS9', 'post-op visits'),
('AV3', 'proc. only allowed'),
('C1', 'allowed as repeat/limited consultation'),
('C2', 'allowed at re-assessment fee'),
('C3', 'allowed at minor assessment fee'),
('C4', 'consultation not allowed with this service - paid as assessment'),
('C5', 'allowed as multiple systems assessment'),
('C6', 'allowed as Type 2 admission assessment'),
('C7', 'an admission assessment (C003A) or general re-assessment (C004A) may not be claimed by any physician within 30 days following a pr-dental/pre-operative assessment'),
('C8', 'Payment reduce to geriatric consultation fee ??? maximum number of comprehensive geriatric consultation has been reached '),
('C9', 'Allowed as in-patient interim admission orders ??? initial assessment already claimed by other physician'),
('CNA', 'Counselling NOT Allowed'),
('COA', 'counseling not allowed'),
('code', 'description'),
('D1', 'allowed as repeat procedure - initial procedure previously claimed'),
('D2', 'additional procedures allowed at 50%'),
('D3', 'not allowed in addition to visit fee'),
('D4', 'procedure allowed at 50% with visit'),
('D5', 'procedure already allowed - visit fee adjustment'),
('D6', 'limit of payment for this procedure reached'),
('D7', 'not allowed in addition to other procedure'),
('D8', 'allowed with specific procedures only'),
('D9', 'not allowed to a hospital department'),
('DA', 'maximum for this procedure reached - paid as repeat/chronic procedure'),
('DB', 'Other dialysis procedure already paid'),
('DC', 'procedure paid previously not allowed in addition to this procedure - fee adjusted to pay the difference'),
('DD', 'Not allowed as diadnostic code is unrelated to original eye exam'),
('DE', 'LAB tests already paid - visit fee adjusted'),
('DF', 'Corresponding fee code has not been claimed or was approved at zero'),
('DG', 'diagnostic services for hospital in-patients are not payable on a fee-for-service basis - included in the hospital global budget'),
('DH', 'ventilator support allowed with haemodialysis'),
('DL', 'allowed as laboratory tests in private office'),
('DM', 'Paid/Disallowed in accordance with MOH policy regarding an Emergency Department Equivalent'),
('DN', 'allowed a prudenal block in addition to procedure - as per OHIP policy'),
('DP', 'procedure paid preciously allowed at 50% in addition to this procedure - fee adjusted to pay the difference'),
('DS', 'not allowed ??? mutually exclusive code billed'),
('DT', 'In-patient technical fee not allowed'),
('DV', 'Service is included in Monthly Management Fee for LTC Patient'),
('DX', 'Diagnostic code not eligible with FSC'),
('E1', 'service date prior to start of eligibility'),
('E2', 'incorrect version code for service date'),
('E4', 'service date after the eligibility termination date'),
('E5', 'service date not within an eligible period'),
('EA', 'service date is not within an eligible period- service provided on or after the 20th of this month will not be paid unless eligibility status changes'),
('EB', 'additional payment for the claim shown'),
('EF', 'incorrect version code - services provided on or after the 20th of this month will not be paid unless the current version code is provided'),
('EF1', 'IHF not approved on S/D'),
('EF2', 'IHF not Lic. For FSC on S/D'),
('EF3', 'insured service excl. from IHF'),
('EF4', 'Prov. Not IHF on S/D'),
('EF5', 'ins. Srv. Excl. from #991000'),
('EF7', 'Ref. Phys. # required - IHF SRV'),
('EF8', 'INULLNULL FSC claimed, non IHF'),
('EF9', 'mobile site # required'),
('EH1', 'service. Date <eligibility. Eff. Date'),
('EH2', 'mismatched version code'),
('EH4', 'ser. Date >eligibility. end date'),
('EH5', 'service. Date not in eligibility. Period'),
('ENB', 'unregistered newborn'),
('EP1', 'Enrolment Transaction Not Allow'),
('EP2', 'Cannot Use Q-Code to Enrol/Re-enrol'),
('EP3', 'Incorrect Service Date ??? Check Date Of Enrolment'),
('EP4', 'Enrolment Restriction Applied'),
('EP5', 'Incorrect Fee Code for this Group Type'),
('EPA', 'network billing not approved'),
('EPC', 'patient not rostered/rostered to another network'),
('EPD', 'roster/HRR payment discrepancy'),
('EPE', 'network affiliation error'),
('EPF', 'enrolment date mismatch'),
('EQ1', 'clinic/Dr not on file'),
('EQ2', 'specialty mismatch'),
('EQ3', 'pay sub. Claim- Dr. option'),
('EQ4', 'pay Dr. claim- sub option'),
('EQ5', 'Lab inactive on S/date'),
('EQ6', 'incorrect referral #'),
('EQ8', 'Lab. Not licensed for FSC'),
('EQ9', 'Lab. # not on file'),
('EQA', 'confirm registered spec.'),
('EQB', 'solo practice inact. On S/D'),
('EQC', 'group not registered on HRR'),
('EQD', 'group inactive on S/D'),
('EQE', 'practice not in group on S/D'),
('EQF', 'aff. Practice inactive on S/D'),
('EQG', 'ref. Lab. Not req on HRR'),
('EQH', 'group agreement error on CPDB'),
('EQI', 'contact characteristics error'),
('EQJ', 'Pract. Not Elig. On S/D '),
('EQK', 'MNI Does Not Meet Criteria'),
('EQL', 'Pract. Not Elig. to Claim FSC '),
('EQS', 'Practice Criteria Not Met'),
('ERF', 'Ref. Phys. # currently ineligible for referrals'),
('ESD', 'app. Group affiliNULLNULLn S/D'),
('EV', 'check health card for current version (applicable for service dates prior to Feb 1/93'),
('F1', 'additional fractures/dislocations allowed at 85%'),
('F2', 'allowed in accordance with transferred care'),
('F3', 'previous attempted reductions (open or closed) allowed at 85%'),
('F5', 'two weeks aftercare included in fracture fee'),
('F6', 'allowed as minor/partial assessment'),
('FF', 'additional payment for the claim shown'),
('G1', 'other critical/comprehensive care already paid'),
('GF', 'coverage lapsed - bill patient for future claims'),
('H1', 'Admission assessment or ER assessment already paid'),
('H2', 'allowed as subsequent visit - initial visit previously claimed'),
('H3', 'maximum fee allowed per week after 5th week'),
('H4', 'maximum fee allowed per week after 6th week to pediatricians'),
('H5', 'maximum fee allowed per month after the 13th week'),
('H6', 'allowed as supportive or concurrent care'),
('H7', 'allowed as chronic care'),
('H8', 'hospital number and/or admission date required for in-hospital service'),
('H9', 'concurrent care already claimed by another doctor'),
('HA', 'admission assessment claimed by another physician - hospital visit fee applied'),
('HCC', 'Not complex/vulnerable'),
('HF', 'concurrent or supportive care already claimed in period'),
('HM', 'not valid master hosp. # on date of service'),
('I2', 'Service is globally funded'),
('I3', 'FSC is not on the IHF license profile for the date specified'),
('I4', 'record shows service has been rendered by another Practitioner/Group/IHF'),
('I5', 'service is globally funded and FSC is not on IHF license profile'),
('I6', 'Premium not applicable'),
('I8', 'Confirmation not received'),
('J3', 'approved for stale dated processing'),
('J7', 'claim submitted six months after service date'),
('L1', 'this service paid to another laboratory'),
('L2', 'not allowed to non-medical laboratory director'),
('L3', 'not allowed in addition to this laboratory procedure'),
('L4', 'not allowed to attending physicians'),
('L5', 'not allowed in addition to other procedure paid to another laboratory'),
('L6', 'procedure paid previously to another laboratory, not allowed in addition to this procedure - fee adjusted to pay the difference'),
('L7', 'not allowed - referred specimen'),
('L8', 'not to be claimed with prenatal/fetal assessment as of July 1/93'),
('L9', 'laboratory services for hospital in-patients or out-patients are not payable on a fee-for-service basis - included in the hospital budget'),
('LA', 'laboratory service is funded by special laboratory agreement'),
('LS', 'paid in accordance to special laboratory agreement'),
('M1', 'maximum feel allowed for these services has been reached'),
('M2', 'maximum allowance for radiographic examination(s) by 1 or more practitioners'),
('M3', 'Maximum fee allowed for prenatal care'),
('M4', 'maximum fee allowed for these services by 1 or more practitioners has bee reached'),
('M5', 'monthly maximum has been reached'),
('M6', 'maximum fee allowed for special visit premium- additional patient seen'),
('MC', 'Maximum of 2 patient case conferences has been reached in a 12 month period'),
('MN', 'Maximum number of sessions has been reached'),
('MS', 'Maximum allowable for sleep studies in a 12-month period by one physician has been reached'),
('MX', 'Maximum of 2artroscopy ???R??? codes with E595 has been reached'),
('O1', 'fee for obstetric care apportioned'),
('O2', 'previous prenatal care already claimed'),
('O3', 'previous prenatal care already claimed by another doctor'),
('O4', 'office visits relating to pregnancy and claimed prior to delivery included in obstetric fee'),
('O5', 'not allowed in addition to delivery'),
('O6', 'medical induction/stimulating of labour allowed once per pregnancy'),
('O7', 'allowed as subsequent prenatal visit - initial prenatal visit already claimed'),
('O8', 'allowed once per pregnancy'),
('O9', 'not allowed in addition to post-natal care'),
('P2', 'maximum fee allowed for low birth weight care'),
('P3', 'maximum feel allowed for newborn care'),
('P4', 'fee for newborn care does not apply when newborn baby is ill'),
('P5', 'over-age for pediatric rates of payment'),
('P6', 'over-age for well-baby care'),
('P9', 'Complex New Patient'),
('Q8', 'LAB not licensed to perform this test on date of service'),
('R01', 'missing HSN'),
('R02', 'invalid HSN'),
('R03', 'invalid/missing province code'),
('R04', 'service excluded from RMBS'),
('R05', 'service DT prior 880401/PG/ON'),
('R06', 'wrong provider for RMBS'),
('R07', 'invalid pay type for RMBS'),
('R08', 'invalid referral number'),
('R09', 'claim header 2 missing - RMB'),
('R1', 'only one health exam allowed in a 24-month period'),
('RD', 'duplicate, paid in RMBS'),
('S1', 'bilateral surgery, one stage, allowed at 85% higher than unilateral'),
('S2', 'bilateral surgery, two stage, allowed at 85% higher than unilateral'),
('S3', 'second surgical procedure allowed at 85%'),
('S4', 'procedure fee reduced when paid with related surgery or anesthetic'),
('S5', 'not allowed in addition to major surgical fee'),
('S6', 'allowed as subsequent procedure - initial procedure - initial procedure previously claimed'),
('S7', 'normal preoperative/postoperative care included in surgical fee'),
('SA', 'surgical procedure allowed at consultation fee'),
('SB', 'normal preoperative visit included in surgical fee - visit fee previously paid - surgical fee adjusted'),
('SC', 'not allowed, major preoperative visit already claimed'),
('SD', 'not allowed, team/Assit fee already clamed'),
('SE', 'major preoperative visit previously paid & admission assessment previously paid - surgery reduced by the admission assessment'),
('SR', 'fee reduced based on MOH utilization adjustment - contact your provider'),
('T1', 'fee allowed according to surgery claim'),
('TH', 'fee reduced per HOH payment policy - contact your physician'),
('V02', 'invalid region code'),
('V04', 'error in claim number'),
('V05', 'error - claim # /service date'),
('V07', 'invalid practice number'),
('V08', 'invalid specialty code'),
('V09', 'invalid referral number'),
('V1', 'allowed as repeat assessment - initial assessment previously claimed'),
('V10', 'invalid surname'),
('V12', 'invalid first name'),
('V13', 'invalid birth date'),
('V14', 'invalid sex'),
('V16', 'unacceptable diagnostic. Code # of services'),
('V17', 'invalid payment type'),
('V18', 'invalid ADM/ first visit date'),
('V19', 'Invalid Chiro Diag Code'),
('V2', 'allowed as extra patient seen in the home'),
('V20', 'Unaccept. Age/Diag Code'),
('V21', 'diagnostic code required'),
('V22', 'invalid diagnostic code'),
('V23', 'check # of services'),
('V25', 'invalid action code'),
('V26', 'invalid item number'),
('V27', 'supply same action code'),
('V28', 'invalid hospital number'),
('V29', 'Invalid in/out Indicator 1-IN 2-OUT'),
('V3', 'not allowed in addition to procedure fee'),
('V30', 'FSC/DX code combination NAB'),
('V31', 'error in claim header'),
('V33', 'missing payee address'),
('V34', 'invalid service code'),
('V35', 'invalid OOP/00C service'),
('V36', 'check sessional input criteria'),
('V37', 'incomplete payee address'),
('V38', 'inconsistent claim ident.'),
('V39', 'allowed items only 99'),
('V4', 'date of service was not a Saturday, Sunday or a statutory holiday'),
('V40', 'invalid fee schedule code'),
('V41', 'invalid fee billed'),
('V42', 'invalid number of services'),
('V44', 'invalid assessment code'),
('V46', 'invalid fee approved'),
('V47', 'fee not divisible'),
('V48', 'missing explanatory code'),
('V5', 'only 1 OVA allowed within a 12-month period for age 19 & under or 65 & over & one within 24 months for age 20-64'),
('V50', 'SVC DRE pre initial visit'),
('V51', 'invalid location code'),
('V6', 'allowed as minor assessment - initial assessment already claimed'),
('V60', 'invalid explanatory code'),
('V62', 'Invalid Serv Location Indic'),
('V63', 'invalid Ref. Lab. Number'),
('V64', 'Missing Serv Location Indic'),
('V65', 'Missing Master Number'),
('V66', 'Missing Admission Date'),
('V67', 'Missing Mstr No/Adm Date'),
('V68', 'Incorr Serv Location Indic'),
('V69', 'Serv Dte Invalid for SLI'),
('V7', 'allowed as specific re-assessment fee'),
('V70', 'create date <service date'),
('V8', 'this service paid at lower fee as per OHIP policy'),
('V9', 'only one initial office visit allowed within a 12-month period'),
('V94', 'invalid bill 94 adjustment'),
('V95', 'one bill 94 adjustment per claim'),
('V96', 'invalid bill 147 adjustment'),
('V97', 'one bill147 adjustment per claim'),
('V98', 'Wrong Service Date'),
('VA', 'procedure fee reduced - consultation/visit fees not allowed in addition'),
('VB', 'additional OVA is allowed once within 2nd year of patients aged 20-64 following a periodic OVA'),
('VG', 'only 1 geriatric general assessment premium per patient per 12-month period'),
('VH1', 'health # is invalid'),
('VH2', 'health # is missing'),
('VH3', 'invalid payment program'),
('VH4', 'invalid version code'),
('VH5', 'OHIP# required for service date'),
('VH8', 'HN not registered with MOH'),
('VH9', 'HN Not Regd with MOH'),
('VHA', 'OHIP# part.# not on RPDB for HN'),
('VHO', 'header 2 and HN present'),
('VJ5', 'invalid service date'),
('VJ7', 'stale-dated claim'),
('VM', 'Oculo-visual minor assessment is allowed within 12 consecutive months following a major eye exam'),
('VP', 'Allowed with special visit only'),
('VS', 'date of service was a Sat., Sun, or statutory holiday'),
('VW1', 'invalid WCB service'),
('VX', 'Completexity premium not applicable to visit fee'),
('W3', 'Claims submission > 3 m , will still be processed for payment'),
('X2', 'G.I. Tract includes cline & video tape'),
('X3', 'G.I. Tract includes survey file of abdomen'),
('X4', 'Only one BMD allowed within a 24-month period for low risk patient')
ON DUPLICATE KEY UPDATE description=description;
